feat: table container component add
nl-design-system/utrecht pull request #2189
Opened 2024-03-25 09:21 UTC by scar055

new table container component added for the inline scroll

2024-03-25 16:42 UTC, Robbert requested changes
Ziet er echt heel goed uit, mooie PR!

2024-03-25 16:42 UTC, Robbert commented on packages/component-library-react/src/TableContainer.test.tsx
> +  it('renders an table container element', () => {
"table container element" ➝ "div container element"

2024-03-25 16:42 UTC, Robbert commented on packages/component-library-react/src/TableContainer.tsx
> +export interface TableContainerProps extends HTMLAttributes<HTMLTableElement> {
`HTMLTableElement` ➝ `HTMLDivElement`?

2024-03-25 16:42 UTC, Robbert commented on components/table/css/index.scss
> +  overflow: auto;
`overflow` ➝ `overflow-inline`?

2024-03-26 09:18 UTC, scar055 commented on components/table/css/index.scss
> +  overflow: auto;
overflow-inline word niet gezien als een property die bestaat voor dit element.

2024-03-26 15:04 UTC, merged