feat: metadata for button
nl-design-system/utrecht pull request #2369
Opened 2024-08-20 07:28 UTC by jeffreylauwers

- Added metadata for button.
- Fixed wrong syntax for border-width.

2024-08-20 19:14 UTC, Robbert requested changes

2024-08-20 19:14 UTC, Robbert commented on .changeset/invasion-shell-confine.md
> +- Fixed wrong syntax for border-width.
```suggestion
- Fixed wrong design token metadata syntax for border-width.
```

2024-08-20 19:14 UTC, Robbert commented on components/button/src/tokens.json
> +        "type": "lineHeights"
De `syntax` en `type` kloppen niet bij `text-transform`

2024-08-22 07:28 UTC, jeffreylauwers commented on components/button/src/tokens.json
> +        "type": "lineHeights"
Klopt! Aangepast.

2024-08-23 10:41 UTC, Robbert approved these changes

2024-08-23 10:41 UTC, merged