feat: add metadata for drawer
nl-design-system/utrecht pull request #2382
Opened 2024-08-20 12:27 UTC by jeffreylauwers

Added metadata for drawer tokens.

2024-08-20 19:41 UTC, Robbert requested changes

2024-08-20 19:41 UTC, Robbert commented on components/drawer/src/tokens.json
> +            "type": "spacing"
`type` staat niet op de goede plek

2024-08-22 07:10 UTC, jeffreylauwers commented on components/drawer/src/tokens.json
> +            "type": "spacing"
Whoops. En het 'type' was ook niet juist. Dubbelfix.

2024-08-23 10:58 UTC, Robbert approved these changes

2024-08-23 11:10 UTC, Robbert approved these changes

2024-08-23 11:10 UTC, merged