feat: add Number badge as a replacement of Badge counter
nl-design-system/utrecht pull request #2442
Opened 2024-08-28 13:17 UTC by Yolijn

2024-08-28 13:37 UTC, Robbert requested changes
Ben je web-component-library-stencil en storybook-web-component nog vergeten?

2024-08-28 13:37 UTC, Robbert commented on .changeset/new-impalas-wink.md
> +"@utrecht/component-library-vue": patch
```suggestion
"@utrecht/component-library-react": minor
"@utrecht/component-library-vue": minor
```

2024-08-28 14:56 UTC, Yolijn commented on .changeset/new-impalas-wink.md
> +"@utrecht/component-library-vue": minor
```suggestion
"@utrecht/component-library-vue": minor
"@utrecht/web-component-library-stencil": minor
```

2024-08-31 08:05 UTC, Robbert approved these changes

2024-08-31 08:05 UTC, merged