fix: remove background image from custom checkbox focus styles
nl-design-system/utrecht pull request #2675
Opened 2024-12-23 14:17 UTC by MeesoPost

2024-12-23 14:51 UTC, Robbert commented
@MeesoPost Waarom fixt dit iets?

2024-12-23 14:55 UTC, MeesoPost commented
Het  voorkomt dat de checked image al inlaad zodat als je erop focused en de background color veranderd naar een donkere kleur dat de checkmark verschijnt zoals in purmerend 
![image](https://github.com/user-attachments/assets/9b11e247-692e-4d76-9f0e-755ab27d8075)

2024-12-23 15:10 UTC, Yolijn requested changes
Great!

Could you also make sure the background image is not set on other states like `:active`? 

Also this PR needs a changeset to create a new release :)

2024-12-24 01:34 UTC, Robbert commented on .changeset/clean-sloths-lick.md
> +"@utrecht/custom-checkbox-css": minor
```suggestion
"@utrecht/custom-checkbox-css": patch
```

2024-12-24 01:35 UTC, merged